version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
